const datosNotas ={
"1101":[
 {
  "Estudiante": "Acosta Díaz Laura Juliana",
  "Física": "DS",
  "Quimica": "DA",
  "Csociales": "DA",
  "Econ y Pol": "DA",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DA",
  "Lenguaje": "DA",
  "Inglés": "DS",
  "Matemáticas": "DS",
  "Gempresarial": "DA",
  "Tecnología": "DS",
  "Filosofia": "DB",
  "Taller": "DS",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "Andrade Gómez Camila Estefanía",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DA",
  "Ét y Rel": "DB",
  "Edufísica": "DA",
  "Lenguaje": "DBJ",
  "Inglés": "DA",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DB",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Arias Mendoza Samuel Andrés",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DA",
  "Econ y Pol": "DA",
  "Artística": "DA",
  "Ét y Rel": "DA",
  "Edufísica": "DA",
  "Lenguaje": "DB",
  "Inglés": "DA",
  "Matemáticas": "DB",
  "Gempresarial": "DA",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "Benítez Ríos Diego Armando",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DBJ",
  "Ét y Rel": "DBJ",
  "Edufísica": "DB",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DBJ",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Bermúdez Salazar María Fernanda",
  "Física": "DA",
  "Quimica": "DA",
  "Csociales": "DB",
  "Econ y Pol": "DA",
  "Artística": "DB",
  "Ét y Rel": "DA",
  "Edufísica": "DS",
  "Lenguaje": "DB",
  "Inglés": "DA",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DA",
  "Filosofia": "DB",
  "Taller": "DS",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "Calderón Herrera Felipe Eduardo",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DA",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DA",
  "Lenguaje": "DB",
  "Inglés": "DA",
  "Matemáticas": "DA",
  "Gempresarial": "DA",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "Cárdenas Suárez Nicolás Alejandro",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DS",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DA",
  "Gempresarial": "DB",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "Castillo Luna Andrea Sofía",
  "Física": "DA",
  "Quimica": "DA",
  "Csociales": "DA",
  "Econ y Pol": "DA",
  "Artística": "DS",
  "Ét y Rel": "DA",
  "Edufísica": "DS",
  "Lenguaje": "DA",
  "Inglés": "DA",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DB",
  "Filosofia": "DB",
  "Taller": "DA",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "Duarte Molina Tomás Ricardo",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DA",
  "Econ y Pol": "DA",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DA",
  "Lenguaje": "DA",
  "Inglés": "DA",
  "Matemáticas": "DA",
  "Gempresarial": "DA",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "Escobar Vélez Daniela Lucía",
  "Física": "DS",
  "Quimica": "DS",
  "Csociales": "DA",
  "Econ y Pol": "DA",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DA",
  "Lenguaje": "DA",
  "Inglés": "DS",
  "Matemáticas": "DS",
  "Gempresarial": "DS",
  "Tecnología": "DA",
  "Filosofia": "DB",
  "Taller": "DA",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "Fernández Aguilar Jorge Sebastián",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DA",
  "Ét y Rel": "DA",
  "Edufísica": "DB",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DA",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Figueroa Camacho Valentina Isabel",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DB",
  "Ét y Rel": "DB",
  "Edufísica": "DA",
  "Lenguaje": "DBJ",
  "Inglés": "DBJ",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Gaitán Lozano Javier Manuel",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DA",
  "Ét y Rel": "DB",
  "Edufísica": "DB",
  "Lenguaje": "DB",
  "Inglés": "DBJ",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DB",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "García Torres Paula Catalina",
  "Física": "DB",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DA",
  "Artística": "DB",
  "Ét y Rel": "DA",
  "Edufísica": "DS",
  "Lenguaje": "DB",
  "Inglés": "DA",
  "Matemáticas": "DB",
  "Gempresarial": "DA",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "Giraldo Peña Miguel Ángel",
  "Física": "DB",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DA",
  "Ét y Rel": "DB",
  "Edufísica": "DA",
  "Lenguaje": "DBJ",
  "Inglés": "DB",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DA",
  "Filosofia": "DBJ",
  "Taller": "DS",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "Guzmán Romero Luis Alberto",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DS",
  "Ét y Rel": "DB",
  "Edufísica": "DA",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DBJ",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Herrera Quintero Ana Sofía",
  "Física": "DA",
  "Quimica": "DA",
  "Csociales": "DA",
  "Econ y Pol": "DS",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DS",
  "Lenguaje": "DS",
  "Inglés": "DS",
  "Matemáticas": "DS",
  "Gempresarial": "DS",
  "Tecnología": "DB",
  "Filosofia": "DA",
  "Taller": "DA",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "López Vargas Sebastián Mateo",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DA",
  "Econ y Pol": "DB",
  "Artística": "DA",
  "Ét y Rel": "DB",
  "Edufísica": "DA",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DA",
  "Filosofia": "DA",
  "Taller": "DA",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "Martínez Silva Gabriela Renata",
  "Física": "DS",
  "Quimica": "DS",
  "Csociales": "DA",
  "Econ y Pol": "DA",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DS",
  "Lenguaje": "DA",
  "Inglés": "DS",
  "Matemáticas": "DS",
  "Gempresarial": "DS",
  "Tecnología": "DS",
  "Filosofia": "DS",
  "Taller": "DS",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "Medina Fajardo Ricardo Enrique",
  "Física": "DBJ",
  "Quimica": "DBJ",
  "Csociales": "DBJ",
  "Econ y Pol": "DBJ",
  "Artística": "DBJ",
  "Ét y Rel": "DBJ",
  "Edufísica": "DB",
  "Lenguaje": "DBJ",
  "Inglés": "DBJ",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DBJ",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Mejía Cruz Santiago Esteban",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DS",
  "Ét y Rel": "DA",
  "Edufísica": "DA",
  "Lenguaje": "DB",
  "Inglés": "DS",
  "Matemáticas": "DA",
  "Gempresarial": "DA",
  "Tecnología": "DA",
  "Filosofia": "DA",
  "Taller": "DS",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "Mendoza Castaño Elena Marcela",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DA",
  "Artística": "DA",
  "Ét y Rel": "DB",
  "Edufísica": "DB",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DB",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "Molina Páez Carla Eugenia",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DB",
  "Ét y Rel": "DB",
  "Edufísica": "DA",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DB",
  "Gempresarial": "DBJ",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DB",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Moreno Téllez Iván Leonardo",
  "Física": "DS",
  "Quimica": "DS",
  "Csociales": "DA",
  "Econ y Pol": "DA",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DS",
  "Lenguaje": "DA",
  "Inglés": "DS",
  "Matemáticas": "DS",
  "Gempresarial": "DS",
  "Tecnología": "DS",
  "Filosofia": "DS",
  "Taller": "DS",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "Navarro Bustos Óscar Daniel",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DA",
  "Econ y Pol": "DA",
  "Artística": "DA",
  "Ét y Rel": "DB",
  "Edufísica": "DB",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DB",
  "Gempresarial": "DA",
  "Tecnología": "DA",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "Ortega Beltrán Adriana Milena",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DA",
  "Ét y Rel": "DB",
  "Edufísica": "DA",
  "Lenguaje": "DBJ",
  "Inglés": "DB",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DBJ",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Paredes Niño Juan Esteban",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DA",
  "Artística": "DA",
  "Ét y Rel": "DA",
  "Edufísica": "DB",
  "Lenguaje": "DA",
  "Inglés": "DB",
  "Matemáticas": "DB",
  "Gempresarial": "DS",
  "Tecnología": "DB",
  "Filosofia": "DB",
  "Taller": "DS",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "Rojas Pineda Emmanuel Josué",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DBJ",
  "Ét y Rel": "DB",
  "Edufísica": "DB",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DB",
  "Gempresarial": "DBJ",
  "Tecnología": "DA",
  "Filosofia": "DBJ",
  "Taller": "DS",
  "Convivencia": "DA"
 }
],
"1102":[
 {
  "Estudiante": "Aguilar Torres Camilo Sebastián",
  "Física": "DB",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DA",
  "Ét y Rel": "DB",
  "Edufísica": "DA",
  "Lenguaje": "DBJ",
  "Inglés": "DB",
  "Matemáticas": "DA",
  "Gempresarial": "DB",
  "Tecnología": "DA",
  "Filosofia": "DA",
  "Taller": "DA",
  "#NAME?": "DB"
 },
 {
  "Estudiante": "Aldana Pineda Melany Carolina",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DBJ",
  "Econ y Pol": "DB",
  "Artística": "DBJ",
  "Ét y Rel": "DBJ",
  "Edufísica": "DB",
  "Lenguaje": "DBJ",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "#NAME?": "DB"
 },
 {
  "Estudiante": "Álvarez Romero Sofía Valeria",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DA",
  "Artística": "DS",
  "Ét y Rel": "DA",
  "Edufísica": "DS",
  "Lenguaje": "DB",
  "Inglés": "DA",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DS",
  "#NAME?": "DA"
 },
 {
  "Estudiante": "Amaya Castaño Pablo Emilio",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DA",
  "Ét y Rel": "DA",
  "Edufísica": "DS",
  "Lenguaje": "DBJ",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DB",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DS",
  "#NAME?": "DB"
 },
 {
  "Estudiante": "Arango Guzmán Valeria Nicole",
  "Física": "DB",
  "Quimica": "DB",
  "Csociales": "DBJ",
  "Econ y Pol": "DA",
  "Artística": "DA",
  "Ét y Rel": "DB",
  "Edufísica": "DA",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DS",
  "#NAME?": "DB"
 },
 {
  "Estudiante": "Ayala Márquez Leonardo David",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DBJ",
  "Econ y Pol": "DBJ",
  "Artística": "DBJ",
  "Ét y Rel": "DB",
  "Edufísica": "DBJ",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DS",
  "Filosofia": "DBJ",
  "Taller": "DS",
  "#NAME?": "DB"
 },
 {
  "Estudiante": "Barrios Ruiz Martina Alejandra",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DA",
  "Artística": "DA",
  "Ét y Rel": "DB",
  "Edufísica": "DA",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "#NAME?": "DB"
 },
 {
  "Estudiante": "Bautista Vargas Mateo Julián",
  "Física": "DA",
  "Quimica": "DS",
  "Csociales": "DB",
  "Econ y Pol": "DS",
  "Artística": "DA",
  "Ét y Rel": "DS",
  "Edufísica": "DS",
  "Lenguaje": "DA",
  "Inglés": "DA",
  "Matemáticas": "DB",
  "Gempresarial": "DA",
  "Tecnología": "DS",
  "Filosofia": "DA",
  "Taller": "DS",
  "#NAME?": "DS"
 },
 {
  "Estudiante": "Bello Carrillo Daniela Sofía",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DA",
  "Econ y Pol": "DB",
  "Artística": "DB",
  "Ét y Rel": "DB",
  "Edufísica": "DB",
  "Lenguaje": "DBJ",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DB",
  "#NAME?": "DA"
 },
 {
  "Estudiante": "Buitrago Morales Juan David",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DBJ",
  "Artística": "DB",
  "Ét y Rel": "DBJ",
  "Edufísica": "DB",
  "Lenguaje": "DBJ",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "#NAME?": "DB"
 },
 {
  "Estudiante": "Cabrera Núñez Camila Alejandra",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DBJ",
  "Econ y Pol": "DBJ",
  "Artística": "DBJ",
  "Ét y Rel": "DBJ",
  "Edufísica": "DB",
  "Lenguaje": "DBJ",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DA",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "#NAME?": "DB"
 },
 {
  "Estudiante": "Calderón Perea Emanuel Santiago",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DBJ",
  "Econ y Pol": "DB",
  "Artística": "DA",
  "Ét y Rel": "DBJ",
  "Edufísica": "DB",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "#NAME?": "DA"
 },
 {
  "Estudiante": "Camargo Duarte Nicolás Esteban",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DS",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DB",
  "Lenguaje": "DB",
  "Inglés": "DA",
  "Matemáticas": "DA",
  "Gempresarial": "DA",
  "Tecnología": "DS",
  "Filosofia": "DA",
  "Taller": "DA",
  "#NAME?": "DS"
 },
 {
  "Estudiante": "Cano Silva Juliana María",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DBJ",
  "Econ y Pol": "DBJ",
  "Artística": "DBJ",
  "Ét y Rel": "DB",
  "Edufísica": "DB",
  "Lenguaje": "DBJ",
  "Inglés": "DBJ",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "#NAME?": "DB"
 },
 {
  "Estudiante": "Castaño Rivas Thiago Emanuel",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DA",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DB",
  "Lenguaje": "DA",
  "Inglés": "DA",
  "Matemáticas": "DA",
  "Gempresarial": "DB",
  "Tecnología": "DS",
  "Filosofia": "DA",
  "Taller": "DS",
  "#NAME?": "DS"
 },
 {
  "Estudiante": "Cely Méndez Jorge Eduardo",
  "Física": "DS",
  "Quimica": "DA",
  "Csociales": "DA",
  "Econ y Pol": "DS",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DA",
  "Lenguaje": "DS",
  "Inglés": "DS",
  "Matemáticas": "DA",
  "Gempresarial": "DA",
  "Tecnología": "DS",
  "Filosofia": "DA",
  "Taller": "DB",
  "#NAME?": "DS"
 },
 {
  "Estudiante": "Cruz Velásquez Isabella Antonella",
  "Física": "DA",
  "Quimica": "DA",
  "Csociales": "DB",
  "Econ y Pol": "DA",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DS",
  "Lenguaje": "DA",
  "Inglés": "DA",
  "Matemáticas": "DA",
  "Gempresarial": "DB",
  "Tecnología": "DS",
  "Filosofia": "DA",
  "Taller": "DB",
  "#NAME?": "DS"
 },
 {
  "Estudiante": "Delgadillo Acuña Andrés Felipe",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DBJ",
  "Artística": "DB",
  "Ét y Rel": "DBJ",
  "Edufísica": "DBJ",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DBJ",
  "#NAME?": "DB"
 },
 {
  "Estudiante": "Díaz Bermúdez Luciana Gabriela",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DBJ",
  "Econ y Pol": "DBJ",
  "Artística": "DS",
  "Ét y Rel": "DB",
  "Edufísica": "DS",
  "Lenguaje": "DBJ",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DB",
  "#NAME?": "DB"
 },
 {
  "Estudiante": "Espinosa León Ivanna Michelle",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DBJ",
  "Econ y Pol": "DA",
  "Artística": "DA",
  "Ét y Rel": "DB",
  "Edufísica": "DB",
  "Lenguaje": "DB",
  "Inglés": "DBJ",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DA",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "#NAME?": "DB"
 },
 {
  "Estudiante": "Forero Niño Samuel Alejandro",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DBJ",
  "Econ y Pol": "DBJ",
  "Artística": "DBJ",
  "Ét y Rel": "DBJ",
  "Edufísica": "DB",
  "Lenguaje": "DBJ",
  "Inglés": "DBJ",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DBJ",
  "#NAME?": "DB"
 },
 {
  "Estudiante": "Galindo Cárdenas Emiliano José",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DA",
  "Econ y Pol": "DS",
  "Artística": "DS",
  "Ét y Rel": "DA",
  "Edufísica": "DB",
  "Lenguaje": "DA",
  "Inglés": "DA",
  "Matemáticas": "DA",
  "Gempresarial": "DB",
  "Tecnología": "DS",
  "Filosofia": "DA",
  "Taller": "DA",
  "#NAME?": "DS"
 },
 {
  "Estudiante": "García Roldán María Camila",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DA",
  "Econ y Pol": "DA",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DS",
  "Lenguaje": "DB",
  "Inglés": "DA",
  "Matemáticas": "DA",
  "Gempresarial": "DB",
  "Tecnología": "DBJ",
  "Filosofia": "DA",
  "Taller": "DA",
  "#NAME?": "DA"
 },
 {
  "Estudiante": "González Herrera Alan Benjamín",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DA",
  "Artística": "DA",
  "Ét y Rel": "DBJ",
  "Edufísica": "DS",
  "Lenguaje": "DB",
  "Inglés": "DA",
  "Matemáticas": "DA",
  "Gempresarial": "DB",
  "Tecnología": "DS",
  "Filosofia": "DBJ",
  "Taller": "DS",
  "#NAME?": "DA"
 },
 {
  "Estudiante": "Guerrero Fonseca Renata Isabella",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DB",
  "Ét y Rel": "DB",
  "Edufísica": "DB",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DA",
  "Filosofia": "DB",
  "Taller": "DA",
  "#NAME?": "DB"
 },
 {
  "Estudiante": "León Trujillo Carlos Mauricio",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DBJ",
  "Artística": "DA",
  "Ét y Rel": "DBJ",
  "Edufísica": "DA",
  "Lenguaje": "DB",
  "Inglés": "DA",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "#NAME?": "DA"
 },
 {
  "Estudiante": "Lozano Rodríguez Jerónimo Manuel",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DA",
  "Econ y Pol": "DB",
  "Artística": "DA",
  "Ét y Rel": "DB",
  "Edufísica": "DA",
  "Lenguaje": "DA",
  "Inglés": "DB",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DS",
  "#NAME?": "DA"
 },
 {
  "Estudiante": "Maldonado Reyes Laura Valentina",
  "Física": "DA",
  "Quimica": "DA",
  "Csociales": "DB",
  "Econ y Pol": "DS",
  "Artística": "DA",
  "Ét y Rel": "DA",
  "Edufísica": "DA",
  "Lenguaje": "DA",
  "Inglés": "DA",
  "Matemáticas": "DA",
  "Gempresarial": "DA",
  "Tecnología": "DS",
  "Filosofia": "DA",
  "Taller": "DS",
  "#NAME?": "DS"
 }
],
"1103":[
 {
  "Estudiante": "Acuña Moreno Isabella María",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DBJ",
  "Artística": "DBJ",
  "Ét y Rel": "DS",
  "Edufísica": "DA",
  "Lenguaje": "DBJ",
  "Inglés": "DA",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DBJ",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Agudelo Pineda Juan Sebastián",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DBJ",
  "Artística": "DA",
  "Ét y Rel": "DB",
  "Edufísica": "DB",
  "Lenguaje": "DBJ",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DB",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Andrade León Mariana Sofía",
  "Física": "DA",
  "Quimica": "DA",
  "Csociales": "DB",
  "Econ y Pol": "DA",
  "Artística": "DA",
  "Ét y Rel": "DS",
  "Edufísica": "DA",
  "Lenguaje": "DA",
  "Inglés": "DS",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DS",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Arias Ramírez Diego Alejandro",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DBJ",
  "Econ y Pol": "DBJ",
  "Artística": "DB",
  "Ét y Rel": "DB",
  "Edufísica": "DB",
  "Lenguaje": "DBJ",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DBJ",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Barrera Gómez Luciana Isabela",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DBJ",
  "Artística": "DB",
  "Ét y Rel": "DB",
  "Edufísica": "DB",
  "Lenguaje": "DBJ",
  "Inglés": "DB",
  "Matemáticas": "DB",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DBJ",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Beltrán Torres Tomás Eduardo",
  "Física": "DB",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DBJ",
  "Artística": "DA",
  "Ét y Rel": "DA",
  "Edufísica": "DB",
  "Lenguaje": "DB",
  "Inglés": "DA",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Bonilla Escobar Paula Valentina",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DS",
  "Ét y Rel": "DA",
  "Edufísica": "DA",
  "Lenguaje": "DBJ",
  "Inglés": "DB",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DB",
  "Filosofia": "DA",
  "Taller": "DS",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Cárdenas Montoya Nicolás Santiago",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DBJ",
  "Econ y Pol": "DB",
  "Artística": "DA",
  "Ét y Rel": "DB",
  "Edufísica": "DB",
  "Lenguaje": "DB",
  "Inglés": "DBJ",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DS",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Castañeda Romero Alan Gabriel",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DA",
  "Ét y Rel": "DS",
  "Edufísica": "DS",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DBJ",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Chacón Duarte Laura Antonella",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DA",
  "Ét y Rel": "DB",
  "Edufísica": "DB",
  "Lenguaje": "DA",
  "Inglés": "DA",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DB",
  "Filosofia": "DB",
  "Taller": "DS",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Delgado Ruiz Mateo Emiliano",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DB",
  "Ét y Rel": "DS",
  "Edufísica": "DA",
  "Lenguaje": "DB",
  "Inglés": "DA",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DB",
  "Filosofia": "DA",
  "Taller": "DS",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Duarte Figueroa Camila Julieta",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DA",
  "Ét y Rel": "DB",
  "Edufísica": "DB",
  "Lenguaje": "DBJ",
  "Inglés": "DB",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Escamilla Prada Samuel Esteban",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DA",
  "Artística": "DS",
  "Ét y Rel": "DA",
  "Edufísica": "DA",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DS",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Farfán Rodríguez Valentina Sofía",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DBJ",
  "Artística": "DS",
  "Ét y Rel": "DB",
  "Edufísica": "DB",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Gallego Barragán Emiliano Mateo",
  "Física": "DB",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DS",
  "Ét y Rel": "DB",
  "Edufísica": "DA",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DB",
  "Filosofia": "DA",
  "Taller": "DS",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Jiménez Salinas Sofía Gabriela",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DBJ",
  "Econ y Pol": "DBJ",
  "Artística": "DA",
  "Ét y Rel": "DBJ",
  "Edufísica": "DB",
  "Lenguaje": "DBJ",
  "Inglés": "DBJ",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Londoño Cárdenas Santiago Alonso",
  "Física": "DB",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DBJ",
  "Artística": "DB",
  "Ét y Rel": "DB",
  "Edufísica": "DB",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DBJ",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Márquez Gutiérrez Ana María",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DA",
  "Artística": "DS",
  "Ét y Rel": "DA",
  "Edufísica": "DA",
  "Lenguaje": "DBJ",
  "Inglés": "DA",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DS",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Naranjo Cifuentes Gabriel Leonardo",
  "Física": "DB",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DBJ",
  "Artística": "DS",
  "Ét y Rel": "DB",
  "Edufísica": "DA",
  "Lenguaje": "DB",
  "Inglés": "DBJ",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Pérez Muñoz Martina Valeria",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DBJ",
  "Econ y Pol": "DBJ",
  "Artística": "DB",
  "Ét y Rel": "DBJ",
  "Edufísica": "DB",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DB",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Ramírez Ortega Emmanuel Julián",
  "Física": "DB",
  "Quimica": "DB",
  "Csociales": "DBJ",
  "Econ y Pol": "DBJ",
  "Artística": "DB",
  "Ét y Rel": "DB",
  "Edufísica": "DB",
  "Lenguaje": "DB",
  "Inglés": "DA",
  "Matemáticas": "DB",
  "Gempresarial": "DBJ",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DB"
 }
],
"1104":[
 {
  "Estudiante": "Acevedo Rincón Samuel Julián",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DBJ",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DA",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DB",
  "Gempresarial": "DBJ",
  "Tecnología": "DB",
  "Filosofia": "DA",
  "Taller": "DA",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Alarcón Duarte Mariana Lucía",
  "Física": "DBJ",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DBJ",
  "Artística": "DA",
  "Ét y Rel": "DS",
  "Edufísica": "DBJ",
  "Lenguaje": "DBJ",
  "Inglés": "DBJ",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DBJ",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Aparicio Vargas Tomás Felipe",
  "Física": "DBJ",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DBJ",
  "Artística": "DA",
  "Ét y Rel": "DB",
  "Edufísica": "DBJ",
  "Lenguaje": "DBJ",
  "Inglés": "DBJ",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Arévalo Suárez Ana Gabriela",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DA",
  "Lenguaje": "DB",
  "Inglés": "DA",
  "Matemáticas": "DA",
  "Gempresarial": "DB",
  "Tecnología": "DA",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Barreto Lozano Nicolás Emanuel",
  "Física": "DA",
  "Quimica": "DS",
  "Csociales": "DA",
  "Econ y Pol": "DS",
  "Artística": "DA",
  "Ét y Rel": "DA",
  "Edufísica": "DS",
  "Lenguaje": "DB",
  "Inglés": "DA",
  "Matemáticas": "DB",
  "Gempresarial": "DA",
  "Tecnología": "DA",
  "Filosofia": "DB",
  "Taller": "DA",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Becerra Niño Valeria Antonella",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DA",
  "Artística": "DA",
  "Ét y Rel": "DS",
  "Edufísica": "DA",
  "Lenguaje": "DA",
  "Inglés": "DA",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DS",
  "Filosofia": "DB",
  "Taller": "DA",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Bermúdez Cortés Daniel Santiago",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DS",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DA",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DA",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Cabrales Salinas Isabel Fernanda",
  "Física": "DA",
  "Quimica": "DA",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DB",
  "Ét y Rel": "DA",
  "Edufísica": "DA",
  "Lenguaje": "DA",
  "Inglés": "DA",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DB",
  "Filosofia": "DA",
  "Taller": "DA",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Camacho Pineda Juan Esteban",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DA",
  "Econ y Pol": "DBJ",
  "Artística": "DB",
  "Ét y Rel": "DB",
  "Edufísica": "DB",
  "Lenguaje": "DB",
  "Inglés": "DA",
  "Matemáticas": "DB",
  "Gempresarial": "DBJ",
  "Tecnología": "DB",
  "Filosofia": "DB",
  "Taller": "DA",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Cardona Herrera Sara Valentina",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DB",
  "Lenguaje": "DBJ",
  "Inglés": "DBJ",
  "Matemáticas": "DB",
  "Gempresarial": "DBJ",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Castro Mejía Emmanuel David",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DBJ",
  "Econ y Pol": "DBJ",
  "Artística": "DB",
  "Ét y Rel": "DA",
  "Edufísica": "DA",
  "Lenguaje": "DBJ",
  "Inglés": "DBJ",
  "Matemáticas": "DB",
  "Gempresarial": "DBJ",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Cely González Mateo Andrés",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DB",
  "Ét y Rel": "DB",
  "Edufísica": "DB",
  "Lenguaje": "DBJ",
  "Inglés": "DBJ",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DB",
  "Filosofia": "DB",
  "Taller": "DA",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Correa Ramírez Paula Mariana",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DBJ",
  "Econ y Pol": "DB",
  "Artística": "DB",
  "Ét y Rel": "DA",
  "Edufísica": "DB",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DA",
  "Gempresarial": "DA",
  "Tecnología": "DA",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Cuéllar Téllez Thiago Sebastián",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DB",
  "Ét y Rel": "DA",
  "Edufísica": "DA",
  "Lenguaje": "DB",
  "Inglés": "DA",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Dueñas Marín Laura Alejandra",
  "Física": "DA",
  "Quimica": "DA",
  "Csociales": "DA",
  "Econ y Pol": "DA",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DA",
  "Lenguaje": "DA",
  "Inglés": "DB",
  "Matemáticas": "DB",
  "Gempresarial": "DS",
  "Tecnología": "DA",
  "Filosofia": "DBJ",
  "Taller": "DS",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Fonseca Ríos Gabriel Santiago",
  "Física": "DS",
  "Quimica": "DS",
  "Csociales": "DS",
  "Econ y Pol": "DS",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DA",
  "Lenguaje": "DS",
  "Inglés": "DS",
  "Matemáticas": "DS",
  "Gempresarial": "DS",
  "Tecnología": "DA",
  "Filosofia": "DS",
  "Taller": "DS",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "García Fonseca Emilse Mariana",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DA",
  "Artística": "DS",
  "Ét y Rel": "DA",
  "Edufísica": "DB",
  "Lenguaje": "DA",
  "Inglés": "DA",
  "Matemáticas": "DA",
  "Gempresarial": "DS",
  "Tecnología": "DB",
  "Filosofia": "DB",
  "Taller": "DA",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Hernández Bautista Carlos Andrés",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DBJ",
  "Artística": "DB",
  "Ét y Rel": "DA",
  "Edufísica": "DB",
  "Lenguaje": "DBJ",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DB",
  "Filosofia": "DB",
  "Taller": "DA",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "León Rodríguez Sofía Elizabeth",
  "Física": "DA",
  "Quimica": "DS",
  "Csociales": "DB",
  "Econ y Pol": "DS",
  "Artística": "DS",
  "Ét y Rel": "DA",
  "Edufísica": "DB",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Maldonado Peña Emiliano Joaquín",
  "Física": "DA",
  "Quimica": "DS",
  "Csociales": "DB",
  "Econ y Pol": "DA",
  "Artística": "DS",
  "Ét y Rel": "DA",
  "Edufísica": "DB",
  "Lenguaje": "DA",
  "Inglés": "DA",
  "Matemáticas": "DA",
  "Gempresarial": "DA",
  "Tecnología": "DB",
  "Filosofia": "DS",
  "Taller": "DA",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Ordoñez Velásquez Juliana Isabel",
  "Física": "DA",
  "Quimica": "DS",
  "Csociales": "DA",
  "Econ y Pol": "DS",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DS",
  "Lenguaje": "DA",
  "Inglés": "DA",
  "Matemáticas": "DB",
  "Gempresarial": "DA",
  "Tecnología": "DA",
  "Filosofia": "DA",
  "Taller": "DS",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Patiño Cruz Martín Alejandro",
  "Física": "DA",
  "Quimica": "DA",
  "Csociales": "DB",
  "Econ y Pol": "DBJ",
  "Artística": "DS",
  "Ét y Rel": "DBJ",
  "Edufísica": "DBJ",
  "Lenguaje": "DB",
  "Inglés": "DBJ",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DA",
  "Filosofia": "DA",
  "Taller": "DS",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Ríos Bernal Catalina Jimena",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DA",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DBJ",
  "Lenguaje": "DBJ",
  "Inglés": "DB",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DA"
 }
],
"1105":[
 {
  "Estudiante": "Bayona Villasana Jesús Alejandro",
  "Física": "DB",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DA",
  "Ét y Rel": "DB",
  "Edufísica": "DA",
  "Lenguaje": "DBJ",
  "Inglés": "DB",
  "Matemáticas": "DA",
  "Gempresarial": "DB",
  "Tecnología": "DA",
  "Filosofia": "DA",
  "Taller": "DA",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Cardenas Manjarres Yeferson Stiven",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DBJ",
  "Econ y Pol": "DB",
  "Artística": "DBJ",
  "Ét y Rel": "DBJ",
  "Edufísica": "DB",
  "Lenguaje": "DBJ",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Carrasco Dominguez Marivy Del Valle",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DA",
  "Artística": "DS",
  "Ét y Rel": "DA",
  "Edufísica": "DS",
  "Lenguaje": "DB",
  "Inglés": "DA",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DS",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Carrera Garcia Aaron Moises",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DA",
  "Ét y Rel": "DA",
  "Edufísica": "DS",
  "Lenguaje": "DBJ",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DB",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DS",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Castaño Rodriguez Sofia Neydimar",
  "Física": "DB",
  "Quimica": "DB",
  "Csociales": "DBJ",
  "Econ y Pol": "DA",
  "Artística": "DA",
  "Ét y Rel": "DB",
  "Edufísica": "DA",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DS",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Castellanos Ospina Yuber Andrey",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DBJ",
  "Econ y Pol": "DBJ",
  "Artística": "DBJ",
  "Ét y Rel": "DB",
  "Edufísica": "DBJ",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DS",
  "Filosofia": "DBJ",
  "Taller": "DS",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Castillo Camargo Tatiana Alejandra",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DA",
  "Artística": "DA",
  "Ét y Rel": "DB",
  "Edufísica": "DA",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Cordero Infante Elias Abiezer",
  "Física": "DA",
  "Quimica": "DS",
  "Csociales": "DB",
  "Econ y Pol": "DS",
  "Artística": "DA",
  "Ét y Rel": "DS",
  "Edufísica": "DS",
  "Lenguaje": "DA",
  "Inglés": "DA",
  "Matemáticas": "DB",
  "Gempresarial": "DA",
  "Tecnología": "DS",
  "Filosofia": "DA",
  "Taller": "DS",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "Correa Forero Juan Diego",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DA",
  "Econ y Pol": "DB",
  "Artística": "DB",
  "Ét y Rel": "DB",
  "Edufísica": "DB",
  "Lenguaje": "DBJ",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DB",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Fernandez Piso Luis Alejandro",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DBJ",
  "Artística": "DB",
  "Ét y Rel": "DBJ",
  "Edufísica": "DB",
  "Lenguaje": "DBJ",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Garcia Coronado Leydi Katerine",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DBJ",
  "Econ y Pol": "DBJ",
  "Artística": "DBJ",
  "Ét y Rel": "DBJ",
  "Edufísica": "DB",
  "Lenguaje": "DBJ",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DA",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Gomez Silva Miguel Angel",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DBJ",
  "Econ y Pol": "DB",
  "Artística": "DA",
  "Ét y Rel": "DBJ",
  "Edufísica": "DB",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Gragirena Alayon Scarlet Andrea",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DS",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DB",
  "Lenguaje": "DB",
  "Inglés": "DA",
  "Matemáticas": "DA",
  "Gempresarial": "DA",
  "Tecnología": "DS",
  "Filosofia": "DA",
  "Taller": "DA",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "Matoma Cortes Andres Mauricio",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DBJ",
  "Econ y Pol": "DBJ",
  "Artística": "DBJ",
  "Ét y Rel": "DB",
  "Edufísica": "DB",
  "Lenguaje": "DBJ",
  "Inglés": "DBJ",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Mendez Bautista Laura Valentina",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DA",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DB",
  "Lenguaje": "DA",
  "Inglés": "DA",
  "Matemáticas": "DA",
  "Gempresarial": "DB",
  "Tecnología": "DS",
  "Filosofia": "DA",
  "Taller": "DS",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "Mendoza Patiño Aaron Gabriel",
  "Física": "DS",
  "Quimica": "DA",
  "Csociales": "DA",
  "Econ y Pol": "DS",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DA",
  "Lenguaje": "DS",
  "Inglés": "DS",
  "Matemáticas": "DA",
  "Gempresarial": "DA",
  "Tecnología": "DS",
  "Filosofia": "DA",
  "Taller": "DB",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "Ovalle Gonzalez Albany Mariana",
  "Física": "DA",
  "Quimica": "DA",
  "Csociales": "DB",
  "Econ y Pol": "DA",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DS",
  "Lenguaje": "DA",
  "Inglés": "DA",
  "Matemáticas": "DA",
  "Gempresarial": "DB",
  "Tecnología": "DS",
  "Filosofia": "DA",
  "Taller": "DB",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "Quiroga Malaver Kevin Santiago",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DBJ",
  "Artística": "DB",
  "Ét y Rel": "DBJ",
  "Edufísica": "DBJ",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DBJ",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Ramos Castillo Marco David",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DBJ",
  "Econ y Pol": "DBJ",
  "Artística": "DS",
  "Ét y Rel": "DB",
  "Edufísica": "DS",
  "Lenguaje": "DBJ",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DB",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Rodriguez Chirinos Merbiannys Paola",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DBJ",
  "Econ y Pol": "DA",
  "Artística": "DA",
  "Ét y Rel": "DB",
  "Edufísica": "DB",
  "Lenguaje": "DB",
  "Inglés": "DBJ",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DA",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Rosado Salgado Walter Eduardo",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DBJ",
  "Econ y Pol": "DBJ",
  "Artística": "DBJ",
  "Ét y Rel": "DBJ",
  "Edufísica": "DB",
  "Lenguaje": "DBJ",
  "Inglés": "DBJ",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DBJ",
  "Filosofia": "DBJ",
  "Taller": "DBJ",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Sanchez Leaño Carol Sammantha",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DA",
  "Econ y Pol": "DS",
  "Artística": "DS",
  "Ét y Rel": "DA",
  "Edufísica": "DB",
  "Lenguaje": "DA",
  "Inglés": "DA",
  "Matemáticas": "DA",
  "Gempresarial": "DB",
  "Tecnología": "DS",
  "Filosofia": "DA",
  "Taller": "DA",
  "Convivencia": "DS"
 },
 {
  "Estudiante": "Santarroza Ramirez Yoiner Ismael Josue",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DA",
  "Econ y Pol": "DA",
  "Artística": "DS",
  "Ét y Rel": "DS",
  "Edufísica": "DS",
  "Lenguaje": "DB",
  "Inglés": "DA",
  "Matemáticas": "DA",
  "Gempresarial": "DB",
  "Tecnología": "DBJ",
  "Filosofia": "DA",
  "Taller": "DA",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Silva Rodriguez Angel",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DB",
  "Econ y Pol": "DA",
  "Artística": "DA",
  "Ét y Rel": "DBJ",
  "Edufísica": "DS",
  "Lenguaje": "DB",
  "Inglés": "DA",
  "Matemáticas": "DA",
  "Gempresarial": "DB",
  "Tecnología": "DS",
  "Filosofia": "DBJ",
  "Taller": "DS",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Tocarruncho Cardozo Darly Valentina",
  "Física": "DB",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DB",
  "Artística": "DB",
  "Ét y Rel": "DB",
  "Edufísica": "DB",
  "Lenguaje": "DB",
  "Inglés": "DB",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DA",
  "Filosofia": "DB",
  "Taller": "DA",
  "Convivencia": "DB"
 },
 {
  "Estudiante": "Toro Muñoz Dilan Yohan",
  "Física": "DA",
  "Quimica": "DBJ",
  "Csociales": "DB",
  "Econ y Pol": "DBJ",
  "Artística": "DA",
  "Ét y Rel": "DBJ",
  "Edufísica": "DA",
  "Lenguaje": "DB",
  "Inglés": "DA",
  "Matemáticas": "DBJ",
  "Gempresarial": "DBJ",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DA",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Vargas Castellano Yeylyn Tatiana",
  "Física": "DA",
  "Quimica": "DB",
  "Csociales": "DA",
  "Econ y Pol": "DB",
  "Artística": "DA",
  "Ét y Rel": "DB",
  "Edufísica": "DA",
  "Lenguaje": "DA",
  "Inglés": "DB",
  "Matemáticas": "DB",
  "Gempresarial": "DB",
  "Tecnología": "DB",
  "Filosofia": "DBJ",
  "Taller": "DS",
  "Convivencia": "DA"
 },
 {
  "Estudiante": "Villegas Moncayo Stephania Valentina",
  "Física": "DA",
  "Quimica": "DA",
  "Csociales": "DB",
  "Econ y Pol": "DS",
  "Artística": "DA",
  "Ét y Rel": "DA",
  "Edufísica": "DA",
  "Lenguaje": "DA",
  "Inglés": "DA",
  "Matemáticas": "DA",
  "Gempresarial": "DA",
  "Tecnología": "DS",
  "Filosofia": "DA",
  "Taller": "DS",
  "Convivencia": "DS"
 }
]
};
